apiVersion: v1
kind: Service
metadata:
  name: llm-service-global
  namespace: inference
spec:
  selector:
    app: gemma-server
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
# ---
# kind: ServiceExport
# apiVersion: net.gke.io/v1
# metadata:
#  namespace: inference
#  name: llm-service-global