apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: llm-gateway-healthcheck
  namespace: inference
spec:
  default:
    checkIntervalSec: 10
    healthyThreshold: 10
    unhealthyThreshold: 1  
    config:
      httpHealthCheck:
        port: 15021
        portSpecification: USE_FIXED_PORT
        requestPath: /health
      type: HTTP
  targetRef:
    group: net.gke.io
    kind: ServiceImport
    name: llm-service-global
    namespace: inference
