kind: RepoSync
apiVersion: configsync.gke.io/v1beta1
metadata:
  name: whereami-backend
  annotations:
    configmanagement.gke.io/namespace-selector: whereami-backend
    # configsync.gke.io/deletion-propagation-policy: Foreground
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/knee-berts/fleets-next24-demo
    branch: dev
    dir: teams/whereami/backend
    auth: none
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: whereami-backend
  annotations:
    configmanagement.gke.io/namespace-selector: whereami-backend
subjects:
- kind: ServiceAccount
  name: ns-reconciler-whereami-backend-whereami-backend-16
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
