kind: RepoSync
apiVersion: configsync.gke.io/v1beta1
metadata:
  name: inference
  annotations:
    configmanagement.gke.io/namespace-selector: inference
    # configsync.gke.io/deletion-propagation-policy: Foreground
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/knee-berts/fleets-next24-demo
    branch: dev
    dir: teams/llm/inference
    auth: none
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: inference
  annotations:
    configmanagement.gke.io/namespace-selector: inference
subjects:
- kind: ServiceAccount
  name: ns-reconciler-inference-inference-19
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
