apiVersion: v1
kind: Service
metadata:
  name: llm-service-global
spec:
  selector:
    app: gemma-server
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
 namespace: llm
 name: llm-service-global