apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: asm-ingress
 namespace: asm-ingress
spec:
  selector:
    matchLabels:
      asm: ingressgateway
  action: ALLOW
  rules:
  - {}